server:
  port: 8085

spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/webrtc_profile
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
