server:
  port: 8083

spring:
  application:
    name: signaling-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: docker
  autoconfigure:
    exclude: []
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    enabled: true
