server:
  port: 8082

spring:
  application:
    name: room-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/webrtc_room

eureka:
  client:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: docker
  autoconfigure:
    exclude: []
  data:
    mongodb:
      uri: mongodb://mongodb:27017/webrtc_room
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://gateway:8080/eureka/
